export let jobs = [
  {
    number: 0,
    fromNumber: 0,
    loadSite: 0,
    dropSite: 0,
    fromToLoadTime: 0,
    loadTime: 0,
    loadToDropTime: 0,
    dropTime: 0,
    nextLocationNumber: 0,
  },
  {
    number: 1,
    fromNumber: 0,
    loadSite: 0,
    dropSite: 0,
    fromToLoadTime: 0,
    loadTime: 0,
    loadToDropTime: 0,
    dropTime: 0,
    nextLocationNumber: 0,
  },
  {
    number: 2,
    fromNumber: 0,
    loadSite: 0,
    dropSite: 0,
    fromToLoadTime: 0,
    loadTime: 0,
    loadToDropTime: 0,
    dropTime: 0,
    nextLocationNumber: 0,
  },
  {
    number: 3,
    fromNumber: 0,
    fromToLoadTime: 0,
    loadSite: 0,
    loadTime: 0,
    loadToDropTime: 0,
    dropSite: 0,
    dropTime: 0,
    nextLocationNumber: 0,
  },
  {
    number: 4,
    fromNumber: 0,
    loadSite: 0,
    dropSite: 0,
    fromToLoadTime: 0,
    loadTime: 0,
    loadToDropTime: 0,
    dropTime: 0,
    nextLocationNumber: 0,
  },
];

export let loadSite = [
  {
    number: 112,
    facility: "Terminal (Preloaded) ",
    address: "3485 ROY ORR BLVD, GRAND PRAIRIE, TX",
    toTerminal: 0,
    value: 1,
  },
  {
    number: 113,
    facility: "MAGELLAN",
    address: " 4200 SINGLETON BLVD, DALLAS, TX",
    toTerminal: 20,
    value: 2,
  },
  {
    number: 114,
    facility: "MOTIVA",
    address: " 3900 SINGLETON BLVD, DALLAS, TX ",
    toTerminal: 20,
    value: 3,
  },
  {
    number: 115,
    facility: "NUSTAR",
    address: " 1700 MUSTANG CT, SOUTHLAKE, TX ",
    toTerminal: 19,
    value: 4,
  },
  {
    number: 116,
    facility: "ALEDO",
    address: " 6000, I-20, ALEDO, TX",
    toTerminal: 39,
    value: 5,
  },
  {
    number: 117,
    facility: "Cado Mills",
    address: " 2738 CO RD 2168, CADDO MILLS, TX",
    toTerminal: 65,
    value: 6,
  },
];

export let store = [
  {
    number: 0,
    city: "TERMINAL",
    address: "3485 ROY ORR BLVD, GRAND PRAIRIE, TX",
    magellan: 20,
    motiva: 20,
    nustar: 19,
    aledo: 39,
    cado: 65,
    terminal: 0,
  },
  {
    number: 1,
    city: "ARLINGTON",
    address: " 2395 N COLLINS ST ARLINGTON,TX",
    magellan: 19,
    motiva: 19,
    nustar: 20,
    aledo: 35,
    cado: 61,
    terminal: 14,
  },
  {
    number: 2,
    city: "ARLINGTON",
    address: " 2501 SE GREEN OAKS BLVD ARLINGTON,TX",
    magellan: 20,
    motiva: 20,
    nustar: 23,
    aledo: 40,
    cado: 61,
    terminal: 16,
  },
  {
    number: 3,
    city: "ARLINGTON",
    address: " 2525 BROWN BLVD ARLINGTON,TX",
    magellan: 18,
    motiva: 18,
    nustar: 16,
    aledo: 36,
    cado: 59,
    terminal: 10,
  },
  {
    number: 4,
    city: "ARLINGTON",
    address: " 2700 E ABRAM ST ARLINGTON,TX",
    magellan: 18,
    motiva: 18,
    nustar: 19,
    aledo: 38,
    cado: 58,
    terminal: 13,
  },
  {
    number: 5,
    city: "ARLINGTON",
    address: " 4900 W SUBLETT RD ARLINGTON,TX",
    magellan: 28,
    motiva: 28,
    nustar: 31,
    aledo: 32,
    cado: 71,
    terminal: 27,
  },
  {
    number: 6,
    city: "ARLINGTON",
    address: " 920 SIX FLAGS DR ARLINGTON,TX",
    magellan: 15,
    motiva: 15,
    nustar: 18,
    aledo: 36,
    cado: 56,
    terminal: 11,
  },
  {
    number: 7,
    city: "AUBREY",
    address: " 27575 HWY 380 E AUBREY,TX",
    magellan: 44,
    motiva: 44,
    nustar: 42,
    aledo: 75,
    cado: 64,
    terminal: 48,
  },
  {
    number: 8,
    city: "BALCH SPRINGS",
    address: " 13105 SEAGOVILLE RD BALCH SPRINGS,TX",
    magellan: 26,
    motiva: 26,
    nustar: 42,
    aledo: 61,
    cado: 40,
    terminal: 41,
  },
  {
    number: 9,
    city: "BEDFORD",
    address: " 429 BEDFORD RD BEDFORD,TX",
    magellan: 24,
    motiva: 24,
    nustar: 14,
    aledo: 49,
    cado: 65,
    terminal: 14,
  },
  {
    number: 10,
    city: "BENBROOK",
    address: " 8000 SW LOOP 820 BENBROOK,TX",
    magellan: 38,
    motiva: 38,
    nustar: 37,
    aledo: 14,
    cado: 78,
    terminal: 35,
  },
  {
    number: 11,
    city: "CANTON",
    address: " 2256 N TRADE DAYS BLVD CANTON,TX",
    magellan: 66,
    motiva: 66,
    nustar: 82,
    aledo: 110,
    cado: 52,
    terminal: 85,
  },
  {
    number: 12,
    city: "CARROLLTON",
    address: " 2146 N JOSEY LN CARROLLTON,TX",
    magellan: 24,
    motiva: 24,
    nustar: 20,
    aledo: 52,
    cado: 51,
    terminal: 22,
  },
  {
    number: 13,
    city: "CARROLLTON",
    address: " 3905 OLD DENTON RD CARROLLTON,TX",
    magellan: 26,
    motiva: 26,
    nustar: 19,
    aledo: 53,
    cado: 53,
    terminal: 24,
  },
  {
    number: 14,
    city: "CEDAR HILL",
    address: " 210 EAST FM 1382 CEDAR HILL,TX",
    magellan: 23,
    motiva: 23,
    nustar: 34,
    aledo: 51,
    cado: 56,
    terminal: 23,
  },
  {
    number: 15,
    city: "CEDAR HILL",
    address: " 401 E FM 1382 CEDAR HILL,TX",
    magellan: 22,
    motiva: 22,
    nustar: 35,
    aledo: 54,
    cado: 55,
    terminal: 25,
  },
  {
    number: 16,
    city: "CLEBURNE",
    address: " 1701 W HENDERSON ST CLEBURNE,TX",
    magellan: 59,
    motiva: 59,
    nustar: 58,
    aledo: 44,
    cado: 96,
    terminal: 56,
  },
  {
    number: 17,
    city: "COCKRELL HILL",
    address: " 4402 W JEFFERSON BLVD COCKRELL HILL,TX",
    magellan: 10,
    motiva: 10,
    nustar: 25,
    aledo: 47,
    cado: 50,
    terminal: 21,
  },
  {
    number: 18,
    city: "CROSS ROADS",
    address: " 6500 US HWY 380 E CROSS ROADS,TX",
    magellan: 49,
    motiva: 49,
    nustar: 42,
    aledo: 70,
    cado: 79,
    terminal: 43,
  },
  {
    number: 19,
    city: "CROSS ROADS",
    address: " 7500 S US HWY 377 CROSSROADS,TX",
    magellan: 51,
    motiva: 51,
    nustar: 44,
    aledo: 72,
    cado: 80,
    terminal: 49,
  },
  {
    number: 20,
    city: "DALLAS",
    address: "1727 N HASKELL DALLAS,TX",
    magellan: 16,
    motiva: 16,
    nustar: 28,
    aledo: 53,
    cado: 42,
    terminal: 27,
  },
  {
    number: 21,
    city: "DALLAS",
    address: " 12950 COIT RD DALLAS,TX",
    magellan: 22,
    motiva: 22,
    nustar: 23,
    aledo: 53,
    cado: 41,
    terminal: 25,
  },
  {
    number: 22,
    city: "DALLAS",
    address: " 18120 COIT RD DALLAS,TX",
    magellan: 29,
    motiva: 29,
    nustar: 27,
    aledo: 59,
    cado: 43,
    terminal: 29,
  },
  {
    number: 23,
    city: "DALLAS",
    address: " 19109 PRESTON RD DALLAS,TX",
    magellan: 29,
    motiva: 29,
    nustar: 25,
    aledo: 57,
    cado: 45,
    terminal: 28,
  },
  {
    number: 24,
    city: "DALLAS",
    address: " 3010 N WESTMORELAND RD DALLAS,TX",
    magellan: 3,
    motiva: 3,
    nustar: 24,
    aledo: 45,
    cado: 50,
    terminal: 19,
  },
  {
    number: 25,
    city: "DALLAS",
    address: " 3511 W DAVIS ST DALLAS,TX",
    magellan: 8,
    motiva: 8,
    nustar: 27,
    aledo: 47,
    cado: 48,
    terminal: 22,
  },
  {
    number: 26,
    city: "DALLAS",
    address: " 4712 HAVERWOOD LN DALLAS,TX",
    magellan: 26,
    motiva: 26,
    nustar: 26,
    aledo: 58,
    cado: 48,
    terminal: 28,
  },
  {
    number: 27,
    city: "DALLAS",
    address: " 5518 ALPHA RD DALLAS,TX",
    magellan: 22,
    motiva: 22,
    nustar: 23,
    aledo: 54,
    cado: 45,
    terminal: 27,
  },
  {
    number: 28,
    city: "DALLAS",
    address: " 5526 ERL THORNTON FWY DALLAS,TX",
    magellan: 14,
    motiva: 14,
    nustar: 32,
    aledo: 54,
    cado: 36,
    terminal: 29,
  },
  {
    number: 29,
    city: "DALLAS",
    address: " 600 N STEMMONS FWY LAKE DALLAS,TX",
    magellan: 32,
    motiva: 32,
    nustar: 23,
    aledo: 57,
    cado: 63,
    terminal: 30,
  },
  {
    number: 30,
    city: "DALLAS",
    address: " 6506 LAKE JUNE RD DALLAS,TX",
    magellan: 18,
    motiva: 18,
    nustar: 34,
    aledo: 56,
    cado: 43,
    terminal: 35,
  },
  {
    number: 31,
    city: "DALLAS",
    address: " 7887 MCCALLUM BLVD DALLAS,TX",
    magellan: 30,
    motiva: 30,
    nustar: 28,
    aledo: 59,
    cado: 45,
    terminal: 29,
  },
  {
    number: 32,
    city: "DALLAS",
    address: " 8015 C F HAWN FWY DALLAS,TX",
    magellan: 20,
    motiva: 20,
    nustar: 35,
    aledo: 58,
    cado: 42,
    terminal: 36,
  },
  {
    number: 33,
    city: "DALLAS",
    address: " 8181 S LANCASTER RD DALLAS,TX",
    magellan: 22,
    motiva: 22,
    nustar: 36,
    aledo: 56,
    cado: 49,
    terminal: 28,
  },
  {
    number: 34,
    city: "DALLAS",
    address: " 9616 AUDELIA RD DALLAS,TX",
    magellan: 27,
    motiva: 27,
    nustar: 31,
    aledo: 61,
    cado: 39,
    terminal: 32,
  },
  {
    number: 35,
    city: "DUNCANVILLE",
    address: " 1102 S COCKRELL HILL RD DUNCANVILLE,TX",
    magellan: 17,
    motiva: 17,
    nustar: 32,
    aledo: 49,
    cado: 50,
    terminal: 21,
  },
  {
    number: 36,
    city: "DUNCANVILLE",
    address: " 1502 S CLARK RD DUNCANVILLE,TX",
    magellan: 17,
    motiva: 17,
    nustar: 31,
    aledo: 50,
    cado: 56,
    terminal: 21,
  },
  {
    number: 37,
    city: "EULESS",
    address: " 100 S INDUSTRIAL BLVD EULESS,TX",
    magellan: 22,
    motiva: 22,
    nustar: 13,
    aledo: 35,
    cado: 61,
    terminal: 9,
  },
  {
    number: 38,
    city: "EULESS",
    address: " 1000 E HARWOOD RD EULESS,TX",
    magellan: 20,
    motiva: 20,
    nustar: 10,
    aledo: 35,
    cado: 60,
    terminal: 8,
  },
  {
    number: 39,
    city: "EULESS",
    address: " 1091 FULLER WISER RD EULESS,TX",
    magellan: 21,
    motiva: 21,
    nustar: 11,
    aledo: 36,
    cado: 61,
    terminal: 9,
  },
  {
    number: 40,
    city: "FLOWER MOUND",
    address: " 2400 CROSS TIMBERS RD FLOWER MOUND,TX",
    magellan: 31,
    motiva: 31,
    nustar: 19,
    aledo: 52,
    cado: 63,
    terminal: 26,
  },
  {
    number: 41,
    city: "FLOWER MOUND",
    address: " 3300 LONG PRAIRIE RD FLOWER MOUND,TX",
    magellan: 29,
    motiva: 29,
    nustar: 17,
    aledo: 51,
    cado: 63,
    terminal: 25,
  },
  {
    number: 42,
    city: "FORT WORTH",
    address: " 10880 N BEACH ST FORT WORTH,TX",
    magellan: 41,
    motiva: 41,
    nustar: 27,
    aledo: 33,
    cado: 81,
    terminal: 31,
  },
  {
    number: 43,
    city: "FORT WORTH",
    address: " 350 N RIVERSIDE DR FORT WORTH,TX",
    magellan: 30,
    motiva: 30,
    nustar: 23,
    aledo: 22,
    cado: 71,
    terminal: 24,
  },
  {
    number: 44,
    city: "FORT WORTH",
    address: " 4150 BRYANT IRVIN RD FORT WORTH,TX",
    magellan: 36,
    motiva: 36,
    nustar: 36,
    aledo: 18,
    cado: 76,
    terminal: 38,
  },
  {
    number: 45,
    city: "FORT WORTH",
    address: " SWC BLUE MOUND & MEACHAM FORT WORTH,TX",
    magellan: 30,
    motiva: 30,
    nustar: 23,
    aledo: 24,
    cado: 74,
    terminal: 22,
  },
  {
    number: 46,
    city: "FRISCO",
    address: " 12626 EL DORADO PKWY FRISCO,TX",
    magellan: 39,
    motiva: 39,
    nustar: 33,
    aledo: 66,
    cado: 58,
    terminal: 39,
  },
  {
    number: 47,
    city: "FRISCO",
    address: " 249 MAIN ST FRISCO,TX",
    magellan: 39,
    motiva: 39,
    nustar: 32,
    aledo: 65,
    cado: 59,
    terminal: 37,
  },
  {
    number: 48,
    city: "FRISCO",
    address: " 3272 PARKWOOD BLVD FRISCO,TX",
    magellan: 31,
    motiva: 31,
    nustar: 25,
    aledo: 58,
    cado: 52,
    terminal: 31,
  },
  {
    number: 49,
    city: "FRISCO",
    address: " 6529 DALLAS PKWY FRISCO,TX",
    magellan: 32,
    motiva: 32,
    nustar: 24,
    aledo: 60,
    cado: 51,
    terminal: 29,
  },
  {
    number: 50,
    city: "GAINESVILLE",
    address: " 1003 N GRAND AVE GAINESVILLE,TX",
    magellan: 30,
    motiva: 30,
    nustar: 63,
    aledo: 79,
    cado: 93,
    terminal: 66,
  },
  {
    number: 51,
    city: "GRAND PRAIRIE",
    address: " 1622 N STATE HWY 360 GRAND PRAIRIE,TX",
    magellan: 23,
    motiva: 23,
    nustar: 26,
    aledo: 39,
    cado: 65,
    terminal: 18,
  },
  {
    number: 52,
    city: "GRAND PRAIRIE",
    address: " 1729 W POLO RD GRAND PRAIRIE,TX",
    magellan: 19,
    motiva: 19,
    nustar: 28,
    aledo: 45,
    cado: 61,
    terminal: 18,
  },
  {
    number: 53,
    city: "GRAND PRAIRIE",
    address: " 2390 W CAMP WISDOM RD GRAND PRAIRIE,TX",
    magellan: 22,
    motiva: 22,
    nustar: 26,
    aledo: 42,
    cado: 63,
    terminal: 18,
  },
  {
    number: 54,
    city: "GRAND PRAIRIE",
    address: " 2475 W TARRANT RD GRAND PRAIRIE,TX",
    magellan: 14,
    motiva: 14,
    nustar: 21,
    aledo: 37,
    cado: 54,
    terminal: 11,
  },
  {
    number: 55,
    city: "GRAND PRAIRIE",
    address: " 3980 S BELT LINE RD GRAND PRAIRIE,TX",
    magellan: 14,
    motiva: 14,
    nustar: 25,
    aledo: 37,
    cado: 56,
    terminal: 14,
  },
  {
    number: 56,
    city: "GRAND PRAIRIE",
    address: " 4002 S GREAT SOUTHWEST PKWY GRAND PRAIRIE,TX",
    magellan: 18,
    motiva: 18,
    nustar: 24,
    aledo: 37,
    cado: 59,
    terminal: 13,
  },
  {
    number: 57,
    city: "GRAND PRAIRIE",
    address: " 726 E PIONEER PKWY GRAND PRAIRIE,TX",
    magellan: 16,
    motiva: 16,
    nustar: 25,
    aledo: 42,
    cado: 56,
    terminal: 14,
  },
  {
    number: 58,
    city: "GREENVILLE",
    address: " 4801 MOULTON ST GREENVILLE,TX",
    magellan: 58,
    motiva: 58,
    nustar: 78,
    aledo: 114,
    cado: 12,
    terminal: 78,
  },
  {
    number: 59,
    city: "HALTOM CITY",
    address: " 4660 WESTERN CENTER BLVD HALTOM CITY,TX",
    magellan: 35,
    motiva: 35,
    nustar: 26,
    aledo: 29,
    cado: 75,
    terminal: 23,
  },
  {
    number: 60,
    city: "IRVING",
    address: " 101 S MACARTHUR BLVD IRVING,TX",
    magellan: 14,
    motiva: 14,
    nustar: 21,
    aledo: 44,
    cado: 56,
    terminal: 11,
  },
  {
    number: 61,
    city: "IRVING",
    address: " 1401 N BELT LINE RD IRVING,TX",
    magellan: 18,
    motiva: 18,
    nustar: 16,
    aledo: 40,
    cado: 59,
    terminal: 7,
  },
  {
    number: 62,
    city: "IRVING",
    address: " 3001 GATEWAY DR STE 130 IRVING,TX",
    magellan: 17,
    motiva: 17,
    nustar: 12,
    aledo: 43,
    cado: 54,
    terminal: 12,
  },
  {
    number: 63,
    city: "IRVING",
    address: " 3001 GATEWAY DR STE 130 IRVING,TX",
    magellan: 17,
    motiva: 17,
    nustar: 12,
    aledo: 43,
    cado: 54,
    terminal: 12,
  },
  {
    number: 64,
    city: "IRVING",
    address: " 3950 VALLEY VIEW LN IRVING,TX",
    magellan: 19,
    motiva: 19,
    nustar: 15,
    aledo: 39,
    cado: 55,
    terminal: 7,
  },
  {
    number: 65,
    city: "IRVING",
    address: " 5401 N MACARTHUR BLVD IRVING,TX",
    magellan: 16,
    motiva: 16,
    nustar: 15,
    aledo: 47,
    cado: 55,
    terminal: 15,
  },
  {
    number: 66,
    city: "JOSHUA",
    address: " 100 S BROADWAY ST JOSHUA,TX",
    magellan: 53,
    motiva: 53,
    nustar: 51,
    aledo: 37,
    cado: 92,
    terminal: 49,
  },
  {
    number: 67,
    city: "KAUFMAN",
    address: " 2201 S WASHINGTON ST KAUFMAN,TX",
    magellan: 40,
    motiva: 40,
    nustar: 57,
    aledo: 86,
    cado: 50,
    terminal: 52,
  },
  {
    number: 68,
    city: "LANCASTER",
    address: " 903 N DALLAS AVE LANCASTER,TX",
    magellan: 27,
    motiva: 27,
    nustar: 42,
    aledo: 63,
    cado: 51,
    terminal: 35,
  },
  {
    number: 69,
    city: "LITTLE ELM",
    address: " 11801 FM 423 LITTLE ELM,TX",
    magellan: 41,
    motiva: 41,
    nustar: 36,
    aledo: 69,
    cado: 62,
    terminal: 39,
  },
  {
    number: 70,
    city: "LITTLE ELM",
    address: " 26595 E UNIVERSITY DR LITTLE ELM,TX",
    magellan: 49,
    motiva: 49,
    nustar: 41,
    aledo: 74,
    cado: 72,
    terminal: 46,
  },
  {
    number: 71,
    city: "MCKINNEY",
    address: " 1710 S INDEPENDENCE PKWY MCKINNEY,TX",
    magellan: 41,
    motiva: 41,
    nustar: 33,
    aledo: 66,
    cado: 56,
    terminal: 40,
  },
  {
    number: 72,
    city: "MCKINNEY",
    address: " 1801 ELDORADO PKWY MCKINNEY,TX",
    magellan: 42,
    motiva: 42,
    nustar: 34,
    aledo: 68,
    cado: 46,
    terminal: 40,
  },
  {
    number: 73,
    city: "MCKINNEY",
    address: " 2400 VIRGINIA PKWY MCKINNEY,TX",
    magellan: 41,
    motiva: 41,
    nustar: 35,
    aledo: 69,
    cado: 46,
    terminal: 40,
  },
  {
    number: 74,
    city: "MCKINNEY",
    address: " 4991 W UNIVERSITY DR MCKINNEY,TX",
    magellan: 46,
    motiva: 46,
    nustar: 41,
    aledo: 75,
    cado: 48,
    terminal: 47,
  },
  {
    number: 75,
    city: "MCKINNEY",
    address: " 5010 ALMA RD MCKINNEY,TX",
    magellan: 39,
    motiva: 39,
    nustar: 32,
    aledo: 65,
    cado: 52,
    terminal: 37,
  },
  {
    number: 76,
    city: "MCKINNEY",
    address: " 8001 W UNIVERSITY DR MCKINNEY,TX",
    magellan: 48,
    motiva: 48,
    nustar: 41,
    aledo: 74,
    cado: 50,
    terminal: 45,
  },
  {
    number: 77,
    city: "MCKINNEY",
    address: " 801 E UNIVERSITY DR MCKINNEY,TX",
    magellan: 46,
    motiva: 46,
    nustar: 39,
    aledo: 74,
    cado: 38,
    terminal: 46,
  },
  {
    number: 78,
    city: "MELISSA",
    address: " 2545 SAM RAYBURN HWY MELISSA,TX",
    magellan: 49,
    motiva: 49,
    nustar: 43,
    aledo: 78,
    cado: 47,
    terminal: 48,
  },
  {
    number: 79,
    city: "MESQUITE",
    address: " 1135 GROSS RD MESQUITE,TX",
    magellan: 23,
    motiva: 23,
    nustar: 40,
    aledo: 62,
    cado: 33,
    terminal: 37,
  },
  {
    number: 80,
    city: "MESQUITE",
    address: " 1145 IH 30 MESQUITE,TX",
    magellan: 23,
    motiva: 23,
    nustar: 36,
    aledo: 62,
    cado: 32,
    terminal: 37,
  },
  {
    number: 81,
    city: "MESQUITE",
    address: " 1505 S BELT LINE RD MESQUITE,TX",
    magellan: 28,
    motiva: 28,
    nustar: 43,
    aledo: 64,
    cado: 37,
    terminal: 41,
  },
  {
    number: 82,
    city: "MESQUITE",
    address: " 3030 MILITARY PKWY MESQUITE,TX",
    magellan: 25,
    motiva: 25,
    nustar: 43,
    aledo: 64,
    cado: 36,
    terminal: 39,
  },
  {
    number: 83,
    city: "MESQUITE",
    address: " 3341 N TOWN EAST BLVD MESQUITE,TX",
    magellan: 20,
    motiva: 20,
    nustar: 38,
    aledo: 60,
    cado: 34,
    terminal: 34,
  },
  {
    number: 84,
    city: "NORTH RICHLAND HILLS",
    address: " 7100 RUFE SNOW DR NORTH RICHLAND HILLS,TX",
    magellan: 33,
    motiva: 33,
    nustar: 20,
    aledo: 32,
    cado: 74,
    terminal: 23,
  },
  {
    number: 85,
    city: "NORTH RICHLAND HILLS",
    address: " 7601 MID CITIES BLVD NORTH RICHLAND HILLS,TX",
    magellan: 31,
    motiva: 31,
    nustar: 17,
    aledo: 32,
    cado: 71,
    terminal: 20,
  },
  {
    number: 86,
    city: "NORTHLAKE",
    address: " 18501 I-35 W NORTHLAKE,TX",
    magellan: 36,
    motiva: 36,
    nustar: 20,
    aledo: 37,
    cado: 78,
    terminal: 32,
  },
  {
    number: 87,
    city: "PLANO",
    address: " 2200 MCDERMOTT RD PLANO,TX",
    magellan: 38,
    motiva: 38,
    nustar: 32,
    aledo: 65,
    cado: 51,
    terminal: 37,
  },
  {
    number: 88,
    city: "PLANO",
    address: " 301 LEGACY DR PLANO,TX",
    magellan: 33,
    motiva: 33,
    nustar: 33,
    aledo: 64,
    cado: 45,
    terminal: 34,
  },
  {
    number: 89,
    city: "PLANO",
    address: " 7040 W SPRING CREEK PKWY PLANO,TX",
    magellan: 30,
    motiva: 30,
    nustar: 21,
    aledo: 54,
    cado: 51,
    terminal: 26,
  },
  {
    number: 90,
    city: "PLANO",
    address: " 826 LEGACY DR PLANO,TX",
    magellan: 34,
    motiva: 34,
    nustar: 34,
    aledo: 66,
    cado: 46,
    terminal: 35,
  },
  {
    number: 91,
    city: "PROSPER",
    address: " 1411 E UNIVERSITY DR PROSPER,TX",
    magellan: 42,
    motiva: 42,
    nustar: 36,
    aledo: 69,
    cado: 56,
    terminal: 38,
  },
  {
    number: 92,
    city: "QUINLAN",
    address: " 525 HWY 276 QUINLAN,TX",
    magellan: 63,
    motiva: 63,
    nustar: 77,
    aledo: 114,
    cado: 23,
    terminal: 79,
  },
  {
    number: 93,
    city: "RICHARDSON",
    address: " 100 S GREENVILLE AVE RICHARDSON,TX",
    magellan: 25,
    motiva: 25,
    nustar: 28,
    aledo: 58,
    cado: 43,
    terminal: 27,
  },
  {
    number: 94,
    city: "RICHARDSON",
    address: " 102 E ARAPAHO RD RICHARDSON,TX",
    magellan: 26,
    motiva: 26,
    nustar: 30,
    aledo: 59,
    cado: 44,
    terminal: 29,
  },
  {
    number: 95,
    city: "ROANOKE",
    address: " 1116 N HWY 377 ROANOKE,TX",
    magellan: 32,
    motiva: 32,
    nustar: 13,
    aledo: 40,
    cado: 67,
    terminal: 29,
  },
  {
    number: 96,
    city: "ROWLETT",
    address: " 1600 DALROCK RD ROWLETT,TX",
    magellan: 29,
    motiva: 29,
    nustar: 44,
    aledo: 67,
    cado: 25,
    terminal: 43,
  },
  {
    number: 97,
    city: "ROWLETT",
    address: " 1700 DALROCK RD ROWLETT,TX",
    magellan: 29,
    motiva: 29,
    nustar: 43,
    aledo: 67,
    cado: 25,
    terminal: 43,
  },
  {
    number: 98,
    city: "ROWLETT",
    address: " 3601 ROWLETT RD ROWLETT,TX",
    magellan: 30,
    motiva: 30,
    nustar: 42,
    aledo: 70,
    cado: 30,
    terminal: 42,
  },
  {
    number: 99,
    city: "ROWLETT",
    address: " 4902 LAKEVIEW PKWY ROWLETT,TX",
    magellan: 29,
    motiva: 29,
    nustar: 39,
    aledo: 69,
    cado: 29,
    terminal: 38,
  },
  {
    number: 100,
    city: "ROYSE CITY",
    address: "1240 ERBY CAMPBELL BLVD ROYSE CITY,TX",
    magellan: 43,
    motiva: 43,
    nustar: 56,
    aledo: 80,
    cado: 13,
    terminal: 57,
  },
  {
    number: 101,
    city: "SAGINAW",
    address: " 1101 N SAGINAW BLVD SAGINAW,TX",
    magellan: 40,
    motiva: 40,
    nustar: 31,
    aledo: 28,
    cado: 81,
    terminal: 29,
  },
  {
    number: 102,
    city: "SAGINAW",
    address: " 500 S SAGINAW BLVD SAGINAW,TX",
    magellan: 36,
    motiva: 36,
    nustar: 27,
    aledo: 23,
    cado: 78,
    terminal: 25,
  },
  {
    number: 103,
    city: "SEAGOVILLE",
    address: " 531 E MALLOY BRIDGE RD SEAGOVILLE,TX",
    magellan: 30,
    motiva: 30,
    nustar: 46,
    aledo: 72,
    cado: 46,
    terminal: 41,
  },
  {
    number: 104,
    city: "TERRELL",
    address: " 1700 HWY 34 S STE 100 TERRELL,TX",
    magellan: 43,
    motiva: 43,
    nustar: 62,
    aledo: 94,
    cado: 37,
    terminal: 57,
  },
  {
    number: 105,
    city: "TERRELL",
    address: " 1703 HWY 34 TERRELL,TX",
    magellan: 42,
    motiva: 42,
    nustar: 62,
    aledo: 94,
    cado: 37,
    terminal: 57,
  },
  {
    number: 106,
    city: "THE COLONY",
    address: " 5208 S COLONY BLVD THE COLONY,TX",
    magellan: 30,
    motiva: 30,
    nustar: 21,
    aledo: 55,
    cado: 56,
    terminal: 28,
  },
  {
    number: 107,
    city: "THE COLONY",
    address: " 5621 S COLONY BLVD THE COLONY,TX",
    magellan: 30,
    motiva: 30,
    nustar: 21,
    aledo: 55,
    cado: 54,
    terminal: 28,
  },
  {
    number: 108,
    city: "THE COLONY",
    address: " 6801 MAIN ST THE COLONY,TX",
    magellan: 33,
    motiva: 33,
    nustar: 25,
    aledo: 59,
    cado: 59,
    terminal: 31,
  },
  {
    number: 109,
    city: "WAXAHACHIE",
    address: " 1301 N HWY 77 WAXAHACHIE,TX",
    magellan: 33,
    motiva: 33,
    nustar: 47,
    aledo: 57,
    cado: 65,
    terminal: 39,
  },
  {
    number: 110,
    city: "WEATHERFORD",
    address: " 2039 FORT WORTH HWY WEATHERFORD,TX",
    magellan: 53,
    motiva: 53,
    nustar: 50,
    aledo: 13,
    cado: 94,
    terminal: 49,
  },
];
